[package]
name = "png_to_jpg"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"

[profile.release]
opt-level = "z"  # or "s" for less aggressive optimizations
lto = true       # Enable Link Time Optimization
codegen-units = 1
